<?php

/* custom routes generated by CRUD */


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('companies', ['as'=> 'companies.index', 'uses' => 'CompanyController@index']);
Route::post('companies', ['as'=> 'companies.store', 'uses' => 'CompanyController@store']);
Route::get('companies/create', ['as'=> 'companies.create', 'uses' => 'CompanyController@create']);
Route::put('companies/{companies}', ['as'=> 'companies.update', 'uses' => 'CompanyController@update']);
Route::patch('companies/{companies}', ['as'=> 'companies.update', 'uses' => 'CompanyController@update']);
Route::get('companies/{id}/delete', array('as' => 'companies.delete', 'uses' => 'CompanyController@getDelete'));
Route::get('companies/{id}/confirm-delete', array('as' => 'companies.confirm-delete', 'uses' => 'CompanyController@getModalDelete'));
Route::get('companies/{companies}', ['as'=> 'companies.show', 'uses' => 'CompanyController@show']);
Route::get('companies/{companies}/edit', ['as'=> 'companies.edit', 'uses' => 'CompanyController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('hazardlists', ['as'=> 'hazardlists.index', 'uses' => 'HazardlistController@index']);
Route::post('hazardlists', ['as'=> 'hazardlists.store', 'uses' => 'HazardlistController@store']);
Route::get('hazardlists/create', ['as'=> 'hazardlists.create', 'uses' => 'HazardlistController@create']);
Route::put('hazardlists/{hazardlists}', ['as'=> 'hazardlists.update', 'uses' => 'HazardlistController@update']);
Route::patch('hazardlists/{hazardlists}', ['as'=> 'hazardlists.update', 'uses' => 'HazardlistController@update']);
Route::get('hazardlists/{id}/delete', array('as' => 'hazardlists.delete', 'uses' => 'HazardlistController@getDelete'));
Route::get('hazardlists/{id}/confirm-delete', array('as' => 'hazardlists.confirm-delete', 'uses' => 'HazardlistController@getModalDelete'));
Route::get('hazardlists/{hazardlists}', ['as'=> 'hazardlists.show', 'uses' => 'HazardlistController@show']);
Route::get('hazardlists/{hazardlists}/edit', ['as'=> 'hazardlists.edit', 'uses' => 'HazardlistController@edit']);

});
